config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'posts#index' , as: 'home'
  get 'about' => 'pages#about', as:'about'

  resources :posts do
    resources :comments
  end
  #/post/1/comment

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence:true, length:{minimum:5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "Admin" , password:"admin" ,only: [:destroy]
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end

    def destroy 
        @post = Post.find(params[:post_id])
        @comment=@post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About US'
        @content= 'This is the about us pages'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "Admin", password:"admin", except: [:index,:show]
    
    def index
        @posts = Post.all
    end 

    def show
        @post=Post.find(params[:id])
    end 

    def new
        @post = Post.new
    end 
    def create
        #render plain: params[:post].inspect 
        @post =Post.new(post_params)
        if (@post.save)
            redirect_to @post
        else
            render 'new'
        end

    end 

    def destroy 
        @post=Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end 

    def edit
        @post=Post.fi nd(params[:id])
    end

    def update
        @post=Post.find(params[:id])

        if (@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end


    private def post_params
        params.require(:post).permit(:title,:body)
    end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comments.html.erb
<h3> Comments </h3>
<% @post.comments.each do |comment| %>
  <div class="card-header">
  <p><strong> <%= comment.username %> </strong>: <%= comment.body%> 
  <%= link_to "[X]", [comment.post,comment],
  method: :delete,
  data:{confirm: 'Are you soure?'}
  %>

  </p>
  </div> 
<%end %>

app/views/comments/_form.html.erb
<h3> Add comments </h3>
<div class="card card-body bg-light">
<%= form_for ([@post, @post.comments.new]) do |f| %>
  <p>
    <%= f.label :username  %><br>
    <%= f.text_field :username, class: 'form-control' %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body , class: 'form-control' %>
  </p>
 
  <p>
    <%= f.submit class:'btn btn-info'%>
  </p>
<% end %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">

      <div class="container">
        <ul class="nav navbar-nav">
        <li> <%= link_to "Home", home_path %> </li>
        </ul>
         <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Create new article", new_post_path %> </li>
        </ul>
      </div>
    </nav>


<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1> <%=@title%> </h1>
<p> <%=@content%> </p>

app/views/posts/edit.html.erb
<h1> Edit Article </h1>
<%= form_for :post, url: post_path(@post), method: :patch do |form| %>
    
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%=msg%> </div>
        <% end %>
    <% end %>
  <p>
    <%= form.label :title  %><br>
    <%= form.text_field :title, class: 'form-control' %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body , class: 'form-control' %>
  </p>
 
  <p>
    <%= form.submit class:'btn btn-primary'%>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1> Articles </h1>

<% @posts.each do |post| %>
    <div class="card card-body bg-light">
        <h3> <%= post.title %> </h3>
        <p> <%= post.body %> </p>
        <%= link_to "Read more" , post_path(post), :class=> 'btn btn-info' %>
    </div>
    <br>
<% end %>

app/views/posts/new.html.erb
<h1> Add Article </h1>
<%= form_for :post, url: posts_path do |form| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%=msg%> </div>
        <% end %>
    <% end %>
  <p>
    <%= form.label :title  %><br>
    <%= form.text_field :title, class: 'form-control' %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body , class: 'form-control' %>
  </p>
 
  <p>
    <%= form.submit class:'btn btn-primary'%>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1> Post Page </h1>
<h2><%=@post.title%></h2>
<p><%=@post.body%></p>

<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-info'%>
<%= link_to "Delete", post_path(@post), 
method: :delete, data:{confirm: 'Are you sure?'},
:class => 'btn btn-danger'%>

<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form'%>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>